### ISSUE TITLE
VID dataset is hard to download, help

### ISSUE THREAD

**Issue by ZSQflower** [bilylee/SiamFC-TensorFlow#1]
Thank you for your work, however, VID dataset (http://bvisionweb1.cs.unc.edu/ilsvrc2015/ILSVRC2015_VID.tar.gz )is hard for me to download, can you provide an alternative link to download?
Note that the original link for Luca's imdb_video.mat is also unavailable.

**Comment by gongbudaizhe** [comment]
Hi, I downloaded the VID dataset from the official download site [here](http://image-net.org/download-images). I tried your download link, the speed is fine (~700 KB/s).  

In this implementation, imdb_video.mat is not needed.

**Comment by bilylee** [comment]
Hi, I downloaded the VID dataset from the official download site [here](http://bvisionweb1.cs.unc.edu/ilsvrc2015/download-videos-3j16.php#vid). I also tried your download link, the speed is fine (~700 KB/s).

In this implementation, imdb_video.mat is not needed.

**Comment by ZSQflower** [comment]
Thx, I got a copy of this data from another lab. Maybe I'll check my network connections later :)

**Comment by bilylee** [comment]
Glad you got the data : )

**Comment by SMZCC** [comment]
- Hello
- I only ~50 k/s :cry: :cry: :cry: :cry: :sob::sob::sob::sob::sob::sob:
- Are there any other sources ?
