### ISSUE TITLE
怎样画出准确率曲线图

### ISSUE THREAD

**Issue by ZhuYin99** [bilylee/SiamFC-TensorFlow#102]
作者您好，我想画出SiamFC的准确率曲线图，用您在benchmark中的custom version无果后，我开始尝试用jwlim版本的tracker_benchmark，发现这里面的draw_graph.py包括了对目标跟踪精确度的绘制，同时需要改变eval_result.py,seq_config.py等文件，但是我用python tracker_benchmark/draw_graph.py precision命令时，出来的plt图还是空白的，我进去result/OPE/SiamFC/里面，发现all.json文件里面的precisionRateList列表是空的。所以，要想绘制准确率曲线图，就要得到precisionRateList列表里的值，我在benchmark中没找到相关的信息，请问precisionRateList列表里的值是在SiamFC-TensorFlow中进行计算的吗？希望您能帮我解决这个问题，非常感谢！！

**Comment by ghost** [comment]
你好，我想请问一下最后的auc曲线你画出来了吗？我现在这里也是运行是一个空白

**Comment by ZhuYin99** [comment]
画出来了，因为之前没进行tracker_benchmark里的第6步，所以result里面没有OTB100的数据，不能画出曲线
 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Baijiang-Lai"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月16日(星期六) 晚上8:48
 收件人:&nbsp;"bilylee/SiamFC-TensorFlow"<SiamFC-TensorFlow@noreply.github.com&gt;;
 抄送:&nbsp;"Dream It Possible"<764580749@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [bilylee/SiamFC-TensorFlow] 怎样画出准确率曲线图 (#102)

 

 

 
你好，我想请问一下最后的auc曲线你画出来了吗？我现在这里也是运行是一个空白
