### ISSUE TITLE
evaluation on VOT2016

### ISSUE THREAD

**Issue by zhangyujia0223** [bilylee/SiamFC-TensorFlow#12]
Could you give me the introduction about how to evaluate it on VOT2016 by python? (方便的话，中文交流)

**Comment by qimingyudaowenti** [comment]
See [Performing evaluation with VOT toolkit](http://geyao1995.com/fight_against_vot_toolkit/#more)
To get SiamFC VOT2016 result, you need modify `inference/track.py`.
