### ISSUE TITLE
框架问题

### ISSUE THREAD

**Issue by noUmbrella** [bilylee/SiamFC-TensorFlow#23]
你好~看了你tensorflow实现的非常的优美高效。请问一下，有考虑过在pytorch上实现吗？感觉会更简洁呢，为什么不在pytorch上做呢？是这么做过遇到了什么问题吗？

**Comment by bilylee** [comment]
Hi,

我之前尝试过用 pytorch，但 pytorch 并不支持 bicubic upsampling。如果用 bilinear upsampling 来上采样 response map 效果变差。

参考 https://github.com/pytorch/pytorch/issues/918

**Comment by noUmbrella** [comment]
多谢回复！这个bicubic upsampling只是用在测试过程，和训练过程没关系是吧？@bilylee

**Comment by noUmbrella** [comment]
这个问题既然不涉及训练过程，那么完全可以测试过程中用numpy或者opencv解决啊@bilylee

**Comment by bilylee** [comment]
如果用 CPU 版本的上采样，如 scipy 或者 opencv 则速度较慢。
