### ISSUE TITLE
请教联系方式

### ISSUE THREAD

**Issue by jingzhizhang** [bilylee/SiamFC-TensorFlow#25]
尊敬的师兄：
        您好。我是武汉大学国家多媒体中心研一的学生，目前也在做跟踪方向，不知您是否方便加下我的QQ：852370792（师兄的QQ肯定不愿对外公布啦，期盼师兄看到消息可以加下我）。今后有问题想请教您。

**Comment by PeterHuang2015** [comment]
@jingzhizhang 围观群众表示，您能够通过 issue 问的问题最好先在 issue 开始沟通。

**Comment by bilylee** [comment]
hi,

请就具体问题在 issue 上提问，这样大家都能看到，效率更高。谢谢！
