### ISSUE TITLE
matlab版本siamesefc问题

### ISSUE THREAD

**Issue by yangkang779** [bilylee/SiamFC-TensorFlow#26]
大神又来打扰了，我按照siamesefc的matlab版本出现问题，我用的是matlab2015a,matconvnet23,在运行只跟踪的时候他出现这个错误，可是我的路径没错感觉，
function p = env_paths_tracking(p)

    p.net_base_path = '/home/yangkang/yk/siamese-fc/';
    p.seq_base_path = '/home/yangkang/yk/siamese-fc/demo-sequences/vot15_bag/';
csvread总是错，
Error using csvread (line 34)
File not found.

Error in load_video_info (line 21)
	ground_truth = csvread([base_path '/' video '/' 'groundtruth.txt']);

Error in tracker (line 55)
    [imgFiles, targetPosition, targetSize] = load_video_info(p.seq_base_path, p.video);

Error in run_tracker (line 11)
    tracker(params);

**Comment by yangkang779** [comment]
看到你在siamesefc下面和作者的留言就来请教你了，谢谢作者

**Comment by PeterHuang2015** [comment]
@yangkang779 查路径吧，应该已经搞定了？

**Comment by yangkang779** [comment]
哈哈，解决了，谢谢啊
