### ISSUE TITLE
How do you get 'num_examples_per_epoch'=5.32e4?

### ISSUE THREAD

**Issue by yl1991** [bilylee/SiamFC-TensorFlow#29]
Hi Bily, 
can I ask how did you obtain the constant 'num_examples_per_epoch' in your config file?
I looked into the training dataset by the following code snippet,
```
dataset = VID('data/train_imdb.pickle', 100)
print(dataset.epoch_size) # output is 8418
```

The epoch size is 8418 so the number of examples per epoch (num_examples_per_epoch) should be
8418 * 8 = 67,344? 

Can you tell me if I mistook anything?
Best regards,
Yiming

**Comment by bilylee** [comment]
Hi,

It is directly taken from https://github.com/bertinetto/siamese-fc/blob/f586d4e32091184240ab7b496ea4df9cb81dd001/training/experiment.m#L24
