### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by zlj199502** [bilylee/SiamFC-TensorFlow#31]
from utils.misc_utils import get
这句出现cannot import name 'misc_utils'这个错误是为什么呀

**Comment by PeterHuang2015** [comment]
插句话，这种只能您本机自查了，作者开源项目但不是要给每个使用者像对客户一样服务。。。看你说的情况，一般是路径问题，比如你直接在 experiments 目录里运行，而不是 python experiments/某个训练脚本。

**Comment by zlj199502** [comment]
好的昂～谢谢你哦
