### ISSUE TITLE
about time-consuming

### ISSUE THREAD

**Issue by lcaikk1314** [bilylee/SiamFC-TensorFlow#35]
Hello，Thanks for your share very much.
I meet a question:when I experiment with your work on GTX1080, it gave 40fps, but you gave 120fps, can you tell me why? I have changed nothing...

**Comment by bilylee** [comment]
My setup:
1. SSD for storing the OTB dataset.
2. Intel Core i7-5930K Haswell-E 6-Core 3.5GHz CPU
3. GeForce GTX 1080 GPU
4. TensorFlow 1.4.0 which is compiled with CUDA 8.0 and cuDNN 6.0.

Please check if your environment matches this setup.

**Comment by zhangyujia0223** [comment]
@lcaikk1314 @bilylee Could you show me how to compute the speed(fps) of tracking? I just can get the completed tracking time(ms) and the frame number(N), should I compute like this N/ms?
