### ISSUE TITLE
The training time

### ISSUE THREAD

**Issue by hwh3304** [bilylee/SiamFC-TensorFlow#48]
Hi  I notice that your training for the two model SiamFC-3s-color and SiamFC-3s-gray taked about 5 hours. But when I try to tarin a SiamFC-3s-color model, it takes 10 hours with a NVIDIA K80 GPU for 50 epochs. Do you have any idea of this speed droop? Thank you.

**Comment by bilylee** [comment]
Hi,

This is to be expected. ~5 hours is measured using GeForce GTX 1080 GPU which is much faster than a NVIDIA K80 GPU.
