### ISSUE TITLE
SiamFC如何实现框大小的调整

### ISSUE THREAD

**Issue by pageedward** [bilylee/SiamFC-TensorFlow#51]
看了论文中没搞清楚是怎么调整框大小，想请教下，谢谢

**Comment by bilylee** [comment]
你好，

给定新的一帧，SiamFC 依据目标上一帧所在的位置，提取 3 个不同 scale 的搜索框，有最大响应的那个搜索框即为目标所在的 scale，由此调节目标框的大小。注意到，SiamFC 只调节 scale，不调节 aspect ratio。

代码部分请参考：
https://github.com/bilylee/SiamFC-TensorFlow/blob/17f51563f081281fc7d966602d393715e7ecb469/inference/tracker.py#L85-L94

**Comment by pageedward** [comment]
就是说用template去卷积3个不同大小搜索区域，
