### ISSUE TITLE
关于预训练模型的问题

### ISSUE THREAD

**Issue by leadalion** [bilylee/SiamFC-TensorFlow#53]
您好，我想在网上找一些预训练的模型的时候，找到的基本都是.npy和.cpkt的。我看了下您代码中用到的模型是.cpkt的data、mata、index三个文件，我想请问一下，网上的那些单独的一个cpkt文件和您代码中的模型有什么区别，它可以用来作为预训练模型吗。谢谢。

**Comment by bilylee** [comment]
Hi,

.data, .meta, .index are files generated by TensorFlow for saving a model. Please take a look at https://stackoverflow.com/questions/41265035/tensorflow-why-there-are-3-files-after-saving-the-model

For loading pretrained model in other format (.npy, .ckpt, etc.,), you need a bit more work. For an example, please see https://github.com/bilylee/SiamFC-TensorFlow/blob/master/scripts/convert_pretrained_model.py which converts the pretrained model in Matlab to TensorFlow.
