### ISSUE TITLE
作者好，我按照你训练的步骤出了问题，

### ISSUE THREAD

**Issue by yangkang779** [bilylee/SiamFC-TensorFlow#6]
2018-03-03 19:58:51.291709: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'f\362g\0028\367KJ8\2332`\311G9\321'
	 [[Node: DecodeJpeg_1 = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="INTEGER_ACCURATE", fancy_upscaling=true, ratio=1, try_recover_truncated=false](ReadFile_1)]]
ERROR - SiamFC-3s-color-scratch - Failed after 0:00:57!
Traceback (most recent calls WITHOUT Sacred internals):
  File "train_siamese_model.py", line 168, in main
    _, loss, batch_loss = sess.run([train_op, model.total_loss, model.batch_loss])
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'f\362g\0028\367KJ8\2332`\311G9\321'
	 [[Node: DecodeJpeg_1 = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="INTEGER_ACCURATE", fancy_upscaling=true, ratio=1, try_recover_truncated=false](ReadFile_1)]]
	 [[Node: train/IteratorGetNext = IteratorGetNext[output_shapes=[[?,127,127,3], [?,239,239,3]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train/OneShotIterator)]]

我在笔记本上先用cpu测试的，然后通的话在服务器上跑，这和这有关系么？如过作者看到请联系qq：779760348，非常感谢，这个问题找了好几天，实在没办法了，谢谢大神

**Comment by bilylee** [comment]
你好，

这个 BUG 说的是文件格式不正确。请确保 Training 部分的第 5 步，即 python scripts/preprocess_VID_data.py 执行成功了。

**Comment by yangkang779** [comment]
你好，应该是执行成功的了，我直接执行python scripts/preprocess_VID_data.py，也没有报错，没有修改代码，执行得到ILSVRC2015-VID-Curation/Data/VID/train/a b c d e 五个文件夹，其他没有了，这个对么？

**Comment by bilylee** [comment]
这 5 个文件夹里的图片都有吗？

**Comment by yangkang779** [comment]
都有图片的，大约二十多G的，是crop过的图片

**Comment by yangkang779** [comment]
https://www.kaggle.com/c/6800/download/imagenet_object_detection_video_train.tar.gz
我下载的这个数据集，然后执行python scripts/preprocess_VID_data.py的，请问这个数据集对么？

**Comment by bilylee** [comment]
下载的压缩包应该有 86G. 你下载的这个应该没问题。

1. 是一开始就报错还是训练了一些 Step 再报错？
2. 在这一行 https://github.com/bilylee/SiamFC-TensorFlow/blob/17f51563f081281fc7d966602d393715e7ecb469/datasets/dataloader.py#L66
下面加 `print(sample)` 看报错的那一行读的是哪张图片？

**Comment by yangkang779** [comment]
python experiments/SiamFC-3s-color-scratch.py
/home/yang/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO - SiamFC-3s-color-scratch - Running command 'main'
INFO - SiamFC-3s-color-scratch - Started run with ID "8"
INFO - root - nvidia-ml-py is not installed, automatically select gpu is disabled!
INFO - root - preproces -- siamese_fc_color
INFO - root - embedding init method -- kaiming_normal
INFO - root - preproces -- None
2018-03-04 14:28:54.070941: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO - root - Restore from last checkpoint: Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-scratch/model.ckpt-0
INFO:tensorflow:Restoring parameters from Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-scratch/model.ckpt-0
INFO - tensorflow - Restoring parameters from Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-scratch/model.ckpt-0
INFO - root - Train for 332500 steps


.
.
.


/SiamFC-TensorFlow/data/ILSVRC2015-VID-Curation/Data/VID/train/d/ILSVRC2015_train_00805000/000200.01.crop.x.jpg', '/media/yang/\xe6\x96\xb0\xe5\x8a\xa0\xe5\x8d\xb74/SiamFC-TensorFlow/data/ILSVRC2015-VID-Curation/Data/VID/train/d/ILSVRC2015_train_00805000/000208.01.crop.x.jpg']
Traceback (most recent call last):
  File "experiments/SiamFC-3s-color-scratch.py", line 29, in <module>
    '--enforce_clean': False,
  File "/home/yang/.local/lib/python2.7/site-packages/sacred/experiment.py", line 199, in run
    run()
  File "/home/yang/.local/lib/python2.7/site-packages/sacred/run.py", line 229, in __call__
    self.result = self.main_function(*args)
  File "/home/yang/.local/lib/python2.7/site-packages/sacred/config/captured_function.py", line 48, in captured_function
    result = wrapped(*args, **kwargs)
  File "experiments/../train_siamese_model.py", line 169, in main
    loss, batch_loss = sess.run([ model.total_loss, model.batch_loss])
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/yang/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'f\362g\0028\367KJ8\2332`\311G9\321'
	 [[Node: DecodeJpeg_1 = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="INTEGER_ACCURATE", fancy_upscaling=true, ratio=1, try_recover_truncated=false](ReadFile_1)]]
	 [[Node: train/IteratorGetNext = IteratorGetNext[output_shapes=[[?,127,127,3], [?,239,239,3]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](train/OneShotIterator)]]

没有训练就报错了，我打算晚上在服务器上重新再按步骤来一遍，可能是cpu 没使用GPU的原因，我本打算是调通几步再传服务器跑的。谢谢大神指教。

**Comment by bilylee** [comment]
你的图片路径中包含中文字符 \xe6\x96\xb0\xe5\x8a\xa0\xe5\x8d\xb74
也许这是原因？

**Comment by yangkang779** [comment]
嗯嗯，有可能，我再重新处理一下试试，谢谢，

**Comment by yangkang779** [comment]
yangkang@node1:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

你好，请问一下，这个cuda8可以装tensorflow 1.4.0么？我装1.7时候失败的，因为配cuda9，你的tf1.4.0配置环境是什么啊

**Comment by gongbudaizhe** [comment]
可以的。我用的就是 CUDA 8.0.

**Comment by yangkang779** [comment]
非常感谢作者，能训练起来了，谢谢

**Comment by bilylee** [comment]
那就好，不客气 ：）

**Comment by 18191171661** [comment]
@bilylee @yangkang779 ,感谢你贡献了这个代码。但是我在运行python experiments/SiamFC-3s-color-scratch.py 出现了问题，您能抽帮忙看看嘛，谢谢。
问题如下所示：
环境：Linux6.04 Cuda8.0 python2.7 tensorflow1.4
按照https://github.com/bilylee/SiamFC-TensorFlow指令执行，前面都没有出现问题，但是当执行python experiments/SiamFC-3s-color-scratch.py老报错：
![screenshot from 2018-12-18 15-00-22](https://user-images.githubusercontent.com/24646917/50137352-e1bc1480-02d5-11e9-86a4-897b19665a9a.png)
我尝试这在Python3.6 tensorflow1.4下面运行，同样会出现这个问题：
![screenshot from 2018-12-18 15-03-26](https://user-images.githubusercontent.com/24646917/50137437-1af48480-02d6-11e9-9ac1-ca0211263adc.png)
首先，我能确定路径里面没有中文，在网上查找了，没有找到有效的解决方案，希望您能够在业余时间帮忙看一下，谢谢。

**Comment by Neptuneland** [comment]
作者您好，我按照您的步骤训练数据时，显示 “nvidia-ml-py is not installed, automatically select gpu is disabled!”，然后就默认用cpu开始训练，但是nvidia-ml-py这个模块是安装过了的。请问有什么解决办法吗？如果能得到您的回复，将非常感谢您。

**Comment by Thomas-czh** [comment]
> 作者您好，我按照您的步骤训练数据时，显示 “nvidia-ml-py is not installed, automatically select gpu is disabled!”，然后就默认用cpu开始训练，但是nvidia-ml-py这个模块是安装过了的。请问有什么解决办法吗？如果能得到您的回复，将非常感谢您。

你好，请问你这个问题解决了吗
