### ISSUE TITLE
无法import butil

### ISSUE THREAD

**Issue by JoeHoo** [bilylee/SiamFC-TensorFlow#61]
你好bilylee，我在复现benchmark的时候，虽然已经安装了butil，但遇到了No module named 'butil'的问题，请问有什么解决方法吗？
![butil1](https://user-images.githubusercontent.com/24286504/46120804-a6182e00-c243-11e8-8a3f-392a3b2e0bc3.jpg)
![butil2](https://user-images.githubusercontent.com/24286504/46120810-a7e1f180-c243-11e8-8951-e46ce300d417.jpg)

**Comment by bilylee** [comment]
你好，

butil 并非安装包，并不需要 pip install butil。 请用 python 2 再试试。

**Comment by JoeHoo** [comment]
感谢您的回答^_^
