### ISSUE TITLE
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by TouchSkyWf** [bilylee/SiamFC-TensorFlow#65]
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
作者你好，我运行python scripts/download_assets.py时报这个错误，是因为没翻墙吗？

**Comment by bilylee** [comment]
是的。你可以通过翻墙下载好 downoad_assets.py 中的文件后再放到 assets 文件夹。
