### ISSUE TITLE
请问benchmark中tracker_benchmark/trackers/SiamFC需要加入文件吗？

### ISSUE THREAD

**Issue by JoeHoo** [bilylee/SiamFC-TensorFlow#68]
您好，bilylee，又打扰了，我在做OTB评估时，遇到了图片中的问题，好像是因为SiamFC里是空的导致的，所以请问需要在tracker_benchmark/trackers/SiamFC里存放什么文件吗？
![1545217898 1](https://user-images.githubusercontent.com/24286504/50216864-f37ae600-03c1-11e9-8ad0-4c0caa9a492e.jpg)

**Comment by bilylee** [comment]
你好，

tracker_benchmark/trackers/SiamFC 并不需要任何文件。

从 log 上看，此时 SiamFC 已经评估完了，在 load 评估结果之后报错。可以 print 一下 seqs, subResults 看看内容是否合理。
