### ISSUE TITLE
算法问题

### ISSUE THREAD

**Issue by dengyang1** [bilylee/SiamFC-TensorFlow#69]
您好：
我想问个问题，就是在Inference阶段，在得到距离中心点的差值后，为啥要乘以网络步长：
disp_instance_input = disp_instance_feat * self.model_config['embed_config']['stride']
可能我不太明白这个算法

谢谢所做的工作。

**Comment by shuida** [comment]
It can be proved that every point in the response  corresponds to a 87*87 area in the search image. Two adjacent points in the response correspond to  two 87*87 areas whose centers are at a distance of 8. The stride 8=2*2*2 originated from conv1, pool1 and pool2, whose stride are 2.

**Comment by shuida** [comment]
You still need to divide it by upsample_factor and search_scale.

**Comment by dengyang1** [comment]
好的,非常感谢解答 @shuida

**Comment by dengyang1** [comment]
@shuida 打扰一下,假如知道在search image上的被追踪物体的长和宽,怎么才能算出对应到相应的原图片上的物体长和宽呢?
