### ISSUE TITLE
Tracker Benchmark Fails

### ISSUE THREAD

**Issue by maddieLeon** [bilylee/SiamFC-TensorFlow#7]
SiameseFC tracker benchmark fails while running 

echo "tb50" | python tracker_benchmark/run_trackers.py -t SiamFC -s tb50 -e OPE
Have followed instructions as per the git readme file.

With the following message
Input Test name : Starting benchmark for 1 trackers, evalTypes : ['OPE']
1_SiamFC, 1_Basketball:1/1 - OPE
failed to execute SiamFC : (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f5812427248>)
Traceback (most recent call last):
  File "tracker_benchmark/run_trackers.py", line 148, in <module>
    main(sys.argv[1:])
  File "tracker_benchmark/run_trackers.py", line 52, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "tracker_benchmark/run_trackers.py", line 140, in run_trackers
    butil.save_seq_result(seqResults)
  File "/export/livia/home/vision/mkiran/work/Siamese2/tracker_benchmark/scripts/butil/load_results.py", line 9, in save_seq_result
    tracker = result[0].tracker

**Comment by yangkang779** [comment]
Hello, can you train successfully?

**Comment by maddieLeon** [comment]
Yes I can train successfully

**Comment by yangkang779** [comment]
Can you send me the source compression package? thank you very much. Because I follow the author steps procedure error。779760348@qq.com

**Comment by bilylee** [comment]
Hi, 

It looks like some files are missing as the error is IOError(2, 'No such file or directory').

Can you evaluate the pretrained model? Is the path in line 22 and 25 from run_SiamFC.py set correctly?

**Comment by maddieLeon** [comment]
Thanks, Its now solved.  res = eval(funcName) in run_trackers.py was giving the default error message as    'failed to execute run_SiamFC' , but when I ran the eval function outside this try block,I  realized my model.json file was missing. It now runs successfully.
@bilylee Thanks very much, the code has been very useful to me!!!

@yangkang779  I hardly did any changes, the original code for training and benchmark runs for me when I followed the steps from the readme.

**Comment by bilylee** [comment]
Glad it helps : )

**Comment by zhangyujia0223** [comment]
![image](https://user-images.githubusercontent.com/28782048/38226284-b5ae984a-3733-11e8-9881-b6c9e02c19fb.png)
I have checked the absolute path and the model_config.json file, but there is still the error. Could you explain the detail of it? I cannot get it clearly. @maddieLeon @bilylee I want to evaluate the new trained scratch model. Thanks a lot.

**Comment by maddieLeon** [comment]
Did you add run_SiamFC.py into the tracker_benchmark/trackers/SiamFC folder?

**Comment by zhangyujia0223** [comment]
Thanks very much

**Comment by Vincent630** [comment]
> Thanks, Its now solved. res = eval(funcName) in run_trackers.py was giving the default error message as 'failed to execute run_SiamFC' , but when I ran the eval function outside this try block,I realized my model.json file was missing. It now runs successfully.
> @bilylee Thanks very much, the code has been very useful to me!!!
> 
> @yangkang779 I hardly did any changes, the original code for training and benchmark runs for me when I followed the steps from the readme.

hi,i can success evaluate model of siamfc follow the steps from the readme,but i want to evaluate another model named MDNet with the the tool,and i get this 'list out of the range' issues,can you help me to fix this problem ?and i also find that my new model of MDNet have no model.json,is that why i can not evaluate the model of MDNet as a type of tensorflow successfully ? if that is not too bother please let me know how to fix this problem,and i will appreciate it

**Comment by Fine0708** [comment]
Hello, 
I also encounter the same error. What is the model.json file? Where can I find it? 
And can you tell me the detailed solution? I just started, and  learned a little.
Please help me,thanks very much!
