### ISSUE TITLE
can this tool "tracker_benchmark" be ueded for another Algorithms,for example MDNet,which is trained by tensorflwo.

### ISSUE THREAD

**Issue by Vincent630** [bilylee/SiamFC-TensorFlow#70]
i use  your amazing tool which named  "tracker_benchmark" to evaluate the model of MDNet,and i failed to get the result ,can you help me with this problem,when i use this tool i also get the dependent which needed from the SiamFC-TensorFlow,but still can not run successful,this is what it comes when i evaluate.

Input Test name : Starting benchmark for 1 trackers, evalTypes : ['OPE']
1_SiamFC, 1_Basketball:1/1 - OPE
failed to execute SiamFC : (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f5c60834128>)
Traceback (most recent call last):
  File "tracker_benchmark/run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "tracker_benchmark/run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "tracker_benchmark/run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/wenguang.wang/Downloads/tracker_benchmark/scripts/butil/load_results.py", line 9, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

**Comment by bilylee** [comment]
Yes, it can be used to evaluate any other trackers as long as you follow the tracking API.  From the logs, it seems you are still evaluating SiamFC instead of MDNet. 

Once you properly set up MDNet in the tracker benchmark toolkit, it can be evaluated like this:
```bash
python tracker_benchmark/run_trackers.py -t MDNet -s tb100 -e OPE
```
