### ISSUE TITLE
why tracking with the model as a .mat format,but actually we can get a ckpt model when we train from scratch? 

### ISSUE THREAD

**Issue by Vincent630** [bilylee/SiamFC-TensorFlow#72]
i find that we can get a ckpt model but when you tracking you use the model which is a .mat format model,can you tell me why is that?and what makes that happen???thanks a lot

**Comment by bilylee** [comment]
For tracking, we also use the TensorFlow model, not .mat.  Note that we converted the .mat file to .ckpt with 
```bash
python experiments/SiamFC-3s-color-pretrained.py
```

**Comment by HearFishle** [comment]
I want to know how to use my own training network to track

**Comment by bilylee** [comment]
@HearFishle Please open a new issue for your problem. For now, I do not understand what did you mean by "use my own training network to track"
