### ISSUE TITLE
Dimension in comment don't match.

### ISSUE THREAD

**Issue by qimingyudaowenti** [bilylee/SiamFC-TensorFlow#76]
I think the comment below should be `[3, 1, 17, 17, 1]` and next line should be `[3, 17, 17]`. 
https://github.com/bilylee/SiamFC-TensorFlow/blob/c72748765f2a68628bf94667be2ff8608277b7c3/inference/inference_wrapper.py#L196
Are the comments mistake?

**Comment by bilylee** [comment]
Fixed, thanks!
