### ISSUE TITLE
关于target_scale的计算

### ISSUE THREAD

**Issue by qimingyudaowenti** [bilylee/SiamFC-TensorFlow#77]
在跟踪过程中，目标框的大小由`target_scale`决定，但是我不太理解`target_scale`为何这样计算，为何将`"scale_damp"`设置为 0.59。您能说明一下吗？
https://github.com/bilylee/SiamFC-TensorFlow/blob/c4f21d137257cb7685a8e3e74105f9be0d24afb4/inference/tracker.py#L133-L138

**Comment by bilylee** [comment]
因为通过当前帧算出来的 target scale 未必是正确的，所以作者用线性组合来做一个 smooth。这里 smooth 的系数为 0.59，是作者遍历搜索搜出来的。
