### ISSUE TITLE
如何使用自己训练的模型进行跟踪？

### ISSUE THREAD

**Issue by HearFishle** [bilylee/SiamFC-TensorFlow#91]
how can I tracking with the model trainded by meself?

**Comment by bilylee** [comment]
Please set configs below  for tracking a single sequence

https://github.com/bilylee/SiamFC-TensorFlow/blob/c4f21d137257cb7685a8e3e74105f9be0d24afb4/scripts/run_tracking.py#L36

And modify these for evaluation on the OTB benchmark.
 
https://github.com/bilylee/SiamFC-TensorFlow/blob/c4f21d137257cb7685a8e3e74105f9be0d24afb4/benchmarks/run_SiamFC.py#L21-L25
