### ISSUE TITLE
pip install sacred 不成功

### ISSUE THREAD

**Issue by 1633146782** [bilylee/SiamFC-TensorFlow#92]
ERROR: Command errored out with exit status 1:
     command: /home/ailab/anaconda3/envs/tensorflow1.4/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-w4pcmR/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-w4pcmR/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-w4pcmR/pip-egg-info
         cwd: /tmp/pip-req-build-w4pcmR/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-w4pcmR/setup.py", line 42, in <module>
        install_requires=Path("requirements.txt").read_text().splitlines(),
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bilylee** [comment]
Just use `pip install sacred` should be fine. I am not sure why did you get these errors.

**Comment by 1633146782** [comment]
thank you sir!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bilylee"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 下午4:01
收件人: "bilylee/SiamFC-TensorFlow"<SiamFC-TensorFlow@noreply.github.com&gt;; 
抄送: "liujinlong"<1633146782@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bilylee/SiamFC-TensorFlow] pip install sacred 不成功 (#92)




Just use pip install sacred should be fine. I am not sure why did you get these errors.

**Comment by yinruiying** [comment]
你好，我使用pip install sacred命令进行安装，遇到了相同的错误。请问该怎么解决？
ERROR: Command errored out with exit status 1:
     command: /home/yry/miniconda3/envs/py27/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0LZNK4/sacred/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0LZNK4/sacred/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0LZNK4/sacred/pip-egg-info
         cwd: /tmp/pip-install-0LZNK4/sacred/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0LZNK4/sacred/setup.py", line 41, in <module>
        install_requires=Path("requirements.txt").read_text().splitlines(),
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bilylee** [comment]
It seems `sacred` is updated to support python > 3.5 only. You can try to install an older version like `pip install sacred==0.7.5`

**Comment by yinruiying** [comment]
Thank you, i solve it.
