### ISSUE TITLE
使用benchmark时显示input_testname

### ISSUE THREAD

**Issue by HearFishle** [bilylee/SiamFC-TensorFlow#93]
显示input_testname时应该输出什么？发现输入什么都会报错，很疑惑

**Comment by bilylee** [comment]
请严格按照 README 中的步骤执行评估操作。你可能是没有执行如下代码：

`echo "tb100" | python tracker_benchmark/run_trackers.py -t SiamFC -s tb100 -e OPE
`

**Comment by HearFishle** [comment]
> n

感谢你的回复

> 请严格按照 README 中的步骤执行评估操作。你可能是没有执行如下代码：
> 
> `echo "tb100" | python tracker_benchmark/run_trackers.py -t SiamFC -s tb100 -e OPE `

感谢您的解答
