### ISSUE TITLE
How can i use my self-defined sequence to evaluate the model?

### ISSUE THREAD

**Issue by ZeguanXiao** [bilylee/SiamFC-TensorFlow#98]

**Comment by bilylee** [comment]
First of all, make sure the format of your video (image names, groundtruth, etc.) follows the OTB standard. You can refer to `assets/KiteSurf'` or videos in [here](http://cvlab.hanyang.ac.kr/tracker_benchmark/datasets.html)

If you want to evaluate the model on just one sequence, use `scripts/run_tracking.py` and change the input_files to your video path
https://github.com/bilylee/SiamFC-TensorFlow/blob/f572dca95f2b3b2861f54de467259753428e468c/scripts/run_tracking.py#L37

If you have multiple sequences and want to compute the AUC metric. This involves much more effort. Please read the code of the OTB toolkit and figure it out.

**Comment by ZeguanXiao** [comment]
Thanks very much.
